---
title: "The Economics of COVID-19"
# subtitle: "Resource repository"
---
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

There is seemingly infinite amounts of information about the different ways in which the COVID-19 pandemic is impacting the global economy. The purpose of this site is to share some of the resources I've found most useful for helping me to understand the short- and long-term impacts the virus is having on the global economy. The selection is personal, not comprehensive, and very much biased towards my own interests, which are largely focused on international economics and growth, vaccine procurement and distribution, and efforts to prevent the pandemic from accelerating inequalities on international level. Contact details are at the bottom of the page; comments and suggestions are most welcome.  

  
## Collections / Platforms  
  
[VoxEU & CEPR Covid-19](https://voxeu.org/pages/covid-19-page)    
The CEPR research network started publishing on this topic early, and their site has a "real-time" COVID Economics journal, discussion papers, articles and multimedia covering every imaginable aspect of the COVID-19 response. There's no dedicated mailing list or feed for the moment, but new content is added more or less on a regular basis.
  
[NBER Studies related to COVID-19](https://www.nber.org/nber-studies-related-covid-19-pandemic-topic-area)  
NBER has collected all of their working papers on pandemic-related research and grouped them by different topic areas. As per usual, these are all open-access and not-yet peer-reviewed.    
  
[CESifo Economic Research on COVID-19](https://www.cesifo.org/en/economic-research-on-covid-19)  
The latest working papers on all things COVID-19 from the CESifo research network. Very current and organized chronologically.  
    
[C19 Economics](https://c19economics.org/)  
The C19 platform is sponsored by a group of partners coming  more from the health side than the purely economic side. Here, the focus is really on sharing information (academic papers, webinars, discussion forums) specifically on health economics, with a focus towards low- and middle-income countries. Helpfully, they do have a newsletter that you can sign up for, though I've yet to receive much, if anything.    

[CGD Coronavirus Preparedness & Response](https://www.cgdev.org/topics/coronavirus)  
The Center for Global Development is looking at how the pandemic is affecting global development, specifically in low- and middle-income countries. Among other things, there is a lot of very interesting work they are doing costing out different scenarios related to supply chain issues and vaccine distribution.
  
## Podcasts: Series  
    
[Coronavirus Global Update](https://www.bbc.co.uk/programmes/w13xtv39/episodes/downloads)  
Among the general COVID-19 news podcasts, this one from the BBC World Service is daily, but short and sweet at around 5-minutes per episode. As per the title, it's globally focused, and you can sign up to it on all the major podcast platforms.  

[Pandemic Economics](https://bfi.uchicago.edu/podcast/pandemic-economics/)  
"Insights from top economists to help you navigate the economic impact of the COVID-19 crisis. Hosts Tess Vigeland and Eduardo Porter talk to University of Chicago economists about their research, revealing important new ways to make sense of this moment. Economics is at the heart of crucial decisions about how we confront the COVID-19 crisis. Topics range from global trade to the changing meaning of work. Pandemic Economics is produced by the Becker Friedman Institute and Stitcher and is part of the University of Chicago podcast network. Production and original music in this series is by Story Mechanics."  

  
<!-- ## Podcasts: Single episodes   -->

  
## Videos / Webcasts / Courses  
  
* [HarvardX: Confronting COVID-19 - Class 21: Economic Impact/Economic Policy](https://www.youtube.com/watch?v=FrvMOJgFN4k&list=PLDSYr_mbXj9VtUDUNPmMO6VnkagS_YnbP&index=21)  
(12 Nov. 2020) The Harvard Global Health Institute put together an [online course about COVID-19](https://www.youtube.com/playlist?list=PLDSYr_mbXj9VtUDUNPmMO6VnkagS_YnbP) to explore a range of issues and questions related to the pandemic. There are 26 episodes, each covering different topics. I haven't gone through them all, but this episode on the economic impacts of COVID-19 was great, particularly for the nice overview of the impact and response to the virus in the U.S (Karen Dynan), as well as the work the IMF has been doing to better understand the global impact (Gita Gopinath). as well as the episodes on [Global Governance and the WHO](https://www.youtube.com/watch?v=Yjq1zVX1rxI&list=PLDSYr_mbXj9VtUDUNPmMO6VnkagS_YnbP&index=17&t=1s) and [Global Health, Global South](https://www.youtube.com/watch?v=oVGV6JIp5hI) quite informative as well.  
  
* [The Great Lockdown: Dissecting the Economic Effects](https://www.imf.org/external/mmedia/view.aspx?vid=6198779261001). 
(8 Oct. 2020)Interview with Damiano Sandri, co-author of chapter 2 ("Dissecting the Economic Effets") in the IMF World Economic Outlook report for October 2020 about the impact of lockdowns on the global economy.  

    
## Book / Book chapters  
  
Jones, Chad. [COVID-19 and the Macroeconomy](https://web.stanford.edu/~chadj/Macroeconomics_Covid.pdf), (Supplement to *Macroeconomics, 5th edition*). [27 February 2021]  
  
Blanchard, Olivier. [The COVID economic crisis](https://piie-my.sharepoint.com/personal/olivier_blanchard_piie_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Folivier%5Fblanchard%5Fpiie%5Fcom%2FDocuments%2Fchapter%20on%20covid%2E%20%20september%2014%202020%2Epdf&parent=%2Fpersonal%2Folivier%5Fblanchard%5Fpiie%5Fcom%2FDocuments&originalPath=aHR0cHM6Ly9waWllLW15LnNoYXJlcG9pbnQuY29tLzpiOi9wL29saXZpZXJfYmxhbmNoYXJkL0VWNUVxVVBEQ2MxTHFxeE5jb0oxM2JzQnoyb2dzd3NDS3N4X3MxQlJJdmt6cFE_cnRpbWU9V0loSEZGVGsyRWc), (Additional chapter for *Macroeconomics, 8th edition*). [September 2020]  

  
## Reports  

 International Monetary Fund. 2020. [World Economic Outlook: A Long and Difficult Ascent](https://www.imf.org/en/Publications/WEO/Issues/2020/09/30/world-economic-outlook-october-2020#Full%20Report%20and%20Executive%20Summary). Washington, DC, October.  

  
## Research papers  
  
Bloom, D.E., Kuhn, M., Prettner, K., 2020. [*Modern Infectious Diseases: Macroeconomic Impacts and Policy Responses (No. w27757)*](https://www.nber.org/papers/w27757). National Bureau of Economic Research. [August 2020]    
<details>
  <summary>*Abstract*</summary>
We discuss and review literature on the macroeconomic effects of epidemics and pandemics since the late 20th century. First, we cover the role of health in driving economic growth and well-being and discuss standard frameworks for assessing the economic burden of infectious diseases. Second, we sketch a general theoretical framework to evaluate the tradeoffs policymakers must consider when addressing infectious diseases and their macroeconomic repercussions. In so doing, we emphasize the dependence of economic consequences on (i) disease characteristics; (ii) inequalities among individuals in terms of susceptibility, preferences, and income; and (iii) cross-country heterogeneities in terms of their institutional and macroeconomic environments. Third, we study pharmaceutical and nonpharmaceutical policies aimed at mitigating and preventing infectious diseases and their macroeconomic repercussions. Fourth, we discuss the health toll and economic impacts of five infectious diseases: HIV/AIDS, malaria, tuberculosis, influenza, and COVID-19. Although major epidemics and pandemics can take an enormous human toll and impose a staggering economic burden, early and targeted health and economic policy interventions can often mitigate both to a substantial degree.  
</details>
<br>
Bloom, David E., Kuhn, M., Prettner, K., 2018. [*Health and Economic Growth (No. 11939)*](https://www.iza.org/publications/dp/11939/health-and-economic-growth), Discussion Papers. IZA Institute of Labor Economics. [November 2018]
<details>
  <summary>*Abstract*</summary>
The positive cross-country correlation between health and economic growth is well-established, but the underlying mechanisms are complex and difficult to discern. Three issues are of central concern. First, assessing and disentangling causality between health and economic growth is empirically challenging. Second, the relation between health and economic growth changes over the process of economic development. Third, different dimensions of health (mortality vs. morbidity, children's and women's health, and health at older ages) may have different economic effects. 
</details>
<br>

<!-- #### __Machine Learning__ -->

<!-- [An Introduction to Statistical Learning with Applications in R](http://www-bcf.usc.edu/~gareth/ISL) <br> -->
<!-- *Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani* <br> -->
<!-- This book provides a hands-on and R-based introduction to Machine Learning. <br/> -->
<!-- _PDF available online_ -->

<!-- #### __Sparse Models__ -->

<!-- The following two books presents a detailed account of recently developed approaches to estimating models containing a large number of parameters, including the Lasso and versions of it:  -->

<!-- [Statistical Learning with Sparsity - The Lasso and Generalizations](https://web.stanford.edu/~hastie/StatLearnSparsity/)   -->
<!-- *Trevor Hastie, Robert Tibshirani, and Martin Wainwright*   -->
<!-- In book contains an introduction to and a summary of the actively developing field of statistical learning with sparse models.   -->
<!-- _PDF available online_ -->

<!-- [Statistics for High-Dimensional Data - Methods, Theory and Applications](https://www.springer.com/gp/book/9783642201912)    -->
<!-- *Peter Buhlmann, and Sara van de Geer*   -->
<!-- This book brings together methodological concepts, computational algorithms, a -->
<!-- few applications and mathematical theory for high-dimensional statistics.   -->

  
<!-- ## Data / Tools    -->


<!-- ## People to follow -->

<!-- * [Susan Athey](https://www.gsb.stanford.edu/faculty-research/faculty/susan-athey) (Stanford) [<i class="fa fa-twitter"></i> ](https://twitter.com/susan_athey)   -->

<!-- * [Alexandre Belloni](https://faculty.fuqua.duke.edu/~abn5/belloni-index.html) (Duke)   -->

<!-- * [Sendhil Mullainathan](https://www.chicagobooth.edu/faculty/directory/m/sendhil-mullainathan)   (Chicago) [<i class="fa fa-twitter"></i> ](https://twitter.com/m_sendhil)   -->

