---
title: "Vaccines"
---
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

This page collects references and public data I've found on issues related to the global supply, demand, and distribution of COVID-19 vaccines. 

## Collections / Platforms

[ImmunizationEconomics.org](http://immunizationeconomics.org/)  
Originally created in 2015 as part of the EPIC project backed by the Gates Foundation, this platform is intended as a resource for organizations and individuals "dedicated to the field of study relating to the cost, financing, sustainability, efficiency, and value of immunizations throughout the world." There's dedicated COVID-19 pages now, along with newsletters you can subscribe to.  

    
## Podcasts: series  

[The Jab](https://www.economist.com/podcasts/2021/02/22/the-jab-a-new-podcast-from-the-economist)    
Yes, that's right, there's a whole podcast series just on COVID-19 vaccinations now. "The Jab" is produced by the Economist's radio/podcast team, and does pretty much what you would guess--short updates on the latest vaccination news, interviews with key people, updates on vaccination statistics. Despite the subject, it's fairly light, and easy to get through.  

  
## Podcasts: single episodes  

[Patent pools for generic drugs](https://voxeu.org/vox-talks/patent-pools-generic-drugs). *VoxTalks*. 19 February 2021.  
"Diffusion of new drugs is painfully slow in low-income countries. Mark Schankerman tells Tim Phillips about how patent pools accelerate the process, and how we could still do a better job of licensing life-saving medicines."

[Equitable Vaccine Rollout, Policy Support Key to Financial Stability](https://www.imf.org/en/News/Podcasts/All-Podcasts/2021/01/26/gfsr-update). *IMF Podcasts*. 27 January 2021.  
"Many things can happen within the global financial system to disrupt financial stability, and the pandemic is testing most of them. Fabio Natalucci heads the IMF's Global Financial Stability Report, which analyses trends in the world economy and looks for potential vulnerabilities. The latest update identifies the uneven distribution of vaccines across the globe as one of those vulnerabilities, especially for frontier market economies. In this podcast, Natalucci says while the vaccine rollout has boosted hopes of a recovery this year, there are still difficult times ahead."
  
[Michael Kremer: Investing in Vaccines Now Would Buy Time, Save $Billions](https://www.imf.org/en/News/Podcasts/All-Podcasts/2020/10/09/michael-kremer). *IMF Podcasts.* 9 October 2020.    
"In the early 2000s, Nobel Laureate, Michael Kremer helped develop the design of advance market commitment models (AMCs). They were used to incentivize the private sector to work on issues of relevance for the developing world by pledging that if they developed an appropriate vaccine, funds would be available for those countries to purchase it. The approach resulted in billions of dollars being devoted to pneumococcal vaccines for strains common in developing countries, saving hundreds of thousands of lives. Kremer's latest research focuses on how to expedite the production and distribution of the COVID-19 vaccines immediately following successful medical trials. In this podcast, Kremer says at-risk investment into vaccine manufacturing capacity before clinical approval would advance vaccine distribution by 6 months or more."  

  
## Videos / Webcasts / Courses

* ["Vaccine economics: how Covid-19 will disrupt the vaccine market"](https://www.ft.com/video/e6f487f4-a7d9-4e90-b9cb-ef8d25803bec). *Financial Times*. [10 March 2021]    
"The FT explains the business models behind vaccines and asks if the Covid-19 pandemic will fundamentally change the vaccine market. This short documentary features global experts including Bill Gates, the CEOs of Moderna and Gavi, and the lead scientist behind the Oxford/AstraZeneca vaccine"
    
* ["Preparing for a Pandemic: Accelerating Vaccine Availability"](https://bfi.uchicago.edu/insight/multimedia/preparing-for-a-pandemic-accelerating-vaccine-availability/). *Becker Friedman Institute*. [30 January 2021]   
"In a new working paper, Preparing for a Pandemic: Accelerating Vaccine Availability, economists from seven research institutions, the World Bank, and the UK’s foreign Commonwealth and Development Office make the economic case for accelerating the arrival and distribution of COVID-19 vaccines, and they offer a roadmap to get it done. Nobel Laureate Michael Kremer of UChicago and Susan Athey of Stanford Business share key findings of this research, including opportunities to enhance the speed of acquiring and administering vaccines. They also address the economics of advance contracts, the value of making further investments in vaccine capacity now, and the benefits of a vaccine exchange to facilitate the best use of existing doses around the world."
  
<!-- ## Reports   -->

  
## Research papers

#### **Development / production / market design**

Ahuja, A., et al. (2021). [Preparing for a Pandemic: Accelerating Vaccine Availability](https://bfi.uchicago.edu/working-paper/preparing-for-a-pandemic-accelerating-vaccine-availability/). *BFI Working Paper*, NO. 2021-08. [30 January 2021]
<details>
  <summary>*Abstract*</summary>
Vaccinating the world’s population quickly in a pandemic has enormous health and economic benefits. We analyze the problem faced by governments in determining the scale and structure of procurement for vaccines. We analyze alternative approaches to procurement, arguing that buyers should directly fund manufacturing capacity and shoulder most of the risk of failure, while maintaining some direct incentives for speed. We analyzed the optimal portfolio of vaccine investments for countries with different characteristics as well as the implications for international cooperation. Our analysis, considered in light of the experience of 2020, suggests lessons for future pandemics.  
</details>
<br>
Kremer, M., Snyder, C.M. (2020). [Strengthening Incentives for Vaccine Development](https://www.nber.org/reporter/2020number4/strengthening-incentives-vaccine-development). *NBER The Reporter*, 4. [December 2020]  
<details>
  <summary>*Abstract*</summary>
Along with improvements in sanitation and nutrition, vaccines have been given credit for substantial reductions in illness and death. Yet the level of research activity devoted to developing new vaccines, at least prior to COVID-19, raises concerns about whether the incentives to develop vaccines are commensurate with the benefits derived from them. Figure 1 shows counts of Phase 3 clinical trials registered annually from 2006 to 2019 by the National Institutes of Health. The number of vaccine trials (left scale), averaging about 75 per year for infectious diseases, is overshadowed by drug trials (right scale), averaging about 1,950 per year. Annual trials for infectious-disease vaccines trend sharply downward compared with the relatively constant number for drugs and for cancer vaccines. </details>
<br>
McAdams, D., McDade, K.K., Ogbuoji, O., Johnson, M., Dixit, S., Yamey, G., 2020. [Incentivising wealthy nations to participate in the COVID-19 Vaccine Global Access Facility (COVAX): a game theory perspective](https://doi.org/10.1136/bmjgh-2020-003627). *BMJ Glob. Health* 5, e003627. [30 November 2020]  
<details>  
  <summary>*Conclusion*</summary>
The proliferation of bilateral deals between richer nations and COVID-19 vaccine manufacturers is a major threat to ensuring global distribution of vaccines and to achieving herd immunity at a global scale. Such deals cannot be stopped, but insights from a game theory analysis suggest ways in which these deals could be configured to potentially improve the global supply of vaccines, by increasing fungibility of investments, enhancing supply-chain harmonisation and articulating principles for such deals.  
</details>  
<br>
  
#### **Economic impact**

Çakmaklı, C., et al. (2021). [The Economic Case for Global Vaccinations: An Epidemiological Model with International Production Networks](https://www.nber.org/papers/w28395). *NBER Working Paper*, w28395. [January 2021]    
<details>
  <summary>*Abstract*</summary>
COVID-19 pandemic had a devastating effect on both lives and livelihoods in 2020. The arrival of effective vaccines can be a major game changer. However, vaccines are in short supply as of early 2021 and most of them are reserved for the advanced economies. We show that the global GDP loss of not inoculating all the countries, relative to a counterfactual of global vaccinations, is higher than the cost of manufacturing and distributing vaccines globally. We use an economic-epidemiological framework that combines a SIR model with international production and trade networks. Based on this framework, we estimate the costs for 65 countries and 35 sectors. Our estimates suggest that up to 49 percent of the global economic costs of the pandemic in 2021 are borne by the advanced economies even if they achieve universal vaccination in their own countries.  
</details>
<br>
Hafner, M., et al.(2020). [COVID-19 and the cost of vaccine nationalism](https://www.rand.org/pubs/research_reports/RRA769-1.html). *RAND Corporation Research Reports, RR-A769-1.*  
<details>
  <summary>*Abstract*</summary>
Experience shows that, in response to pandemics, national governments tend to follow their own interests instead of pursuing a more globally coordinated approach. This nationalistic behaviour could have negative consequences on how well the COVID-19 global pandemic is managed and contained. A situation in which countries push to get first access to a supply of vaccines, potentially hoarding key components for vaccine production, has been commonly referred to as 'vaccine nationalism'. This report examines how the management of the COVID-19 crisis may be affected by vaccine nationalism and what the associated economic cost would be of inequitable access to vaccines across countries.  
</details>
<br>
<!-- #### **Allocation / Distribution** -->

  
## Data / Tools 
  
[LSHTM VaC tracker](https://vac-lshtm.shinyapps.io/ncov_vaccine_landscape/)  
"In response to the unfolding pandemic and the extraordinary volume and pace of global vaccine research, we developed an online, interactive vaccine tracker hosted by the Vaccine Centre (VaC) at the London School of Hygiene and Tropical Medicine (LSHTM; London, UK). Launched in April 2020, this tracker aims to collate up-to-date information on all COVID-19 vaccine candidates from inception through to deployment, enabling policy makers, researchers, and the public to keep informed of the rapid developments. All code and underlying data for the tracker are freely available and are updated regularly through a [Github repository](https://github.com/vac-lshtm/VaC_tracker)."    
  
For the R users, this is a really nice Shiny app. Code is shared, and data sources are well-[documented](https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(21)00043-7/fulltext).
  
Global Health Centre. (2021). [COVID-19 Vaccine Purchases and Manufacturing Agreements](www.knowledgeportalia.org/covid19-vaccine-arrangements). Graduate Institute of International and Development Studies. Retrieved from: www.knowledgeportalia.org/covid19-vaccine-arrangements  
Dashboard tracking public data on agreements to manufacture, purchase, supply and/or donate Covid-19 vaccines from the Global Health Centre at the Graduate Institute, Geneva. It's not clear to me just yet how much overlap there is between this the Duke or UNICEF platforms covering similar grounds. All data collected available for download in a single, handy Excel file. 


<!-- ## Accounts to follow -->

<!-- * [Susan Athey](https://www.gsb.stanford.edu/faculty-research/faculty/susan-athey) (Stanford) [<i class="fa fa-twitter"></i> ](https://twitter.com/susan_athey)   -->

<!-- * [Alexandre Belloni](https://faculty.fuqua.duke.edu/~abn5/belloni-index.html) (Duke)   -->

<!-- * [Victor Chernozhukov](http://www.mit.edu/~vchern/) (MIT)   -->
